# This docker compose file is for building and running a production version of Massive Decks.
# This uses images built by the project.

version: "3"

networks:
  internal:

services:
  server:
    # Pick your tag wisely for stability. In general, it's best to specify an exact version by commit hash and update manually.
    # Versioned tags are also provided, in order of stability: by version number (major "x", minor "x.y", and patch "x.y.z"), latest-release, latest-prerelease, or latest (head of main).
    image: "ghcr.io/lattyware/massivedecks/server:latest-release"
    environment:
      - NODE_ENV=production
      # This needs to be changed to a secret value.
      # You can run `npm run generate-secret` in the server project to generate an appropriate value.
      - MD_SECRET=CHANGE ME
    networks:
      - internal
    restart: unless-stopped

  client:
    depends_on:
      - server
    # Make sure you always deploy the same tag as the server.
    image: "ghcr.io/lattyware/massivedecks/client:latest-release"
    ports:
      - "80:8080"
    networks:
      - internal
    restart: unless-stopped
